#!/usr/bin/env python
#-*-python-*-

# wctest is a script adapted from the RAT analysis framework used by DEAP/CLEAN and SNO+.
# Written by Stan Seibert <sseibert@hep.upenn.edu>

import sys, os, os.path, shutil, webbrowser, re
from math import sqrt

# for backward compatibility to Python 2.3
try:
    set
except NameError:
    from sets import Set as set

# ROOT changes into whatever directory it finds in the command line args
_argv = sys.argv
sys.argv = sys.argv[:1]
import ROOT
from ROOT import gROOT, gSystem, TFile, TH1, TCanvas, kRed, kBlue, kDashed
sys.argv = _argv

gROOT.SetBatch(True)
gROOT.SetStyle('Plain')
gSystem.Load(os.path.join(os.path.dirname(sys.argv[0]), '../libWCSimRoot.so'))
TH1.SetDefaultSumw2()

def target_needs_update(target, sources):
    if not os.path.exists(target):
        return True
    else:
        target_date = os.path.getmtime(target)
        
    for source in sources:
        if target_date < os.path.getmtime(source):
            return True
    
    return False

def find_outfile_name(filename):
    f = file(filename).read()
    match = re.search(r'/WCSimIO/RootFile\s(.+)', f)
    if match:
        return match.group(1)
    else:
        return None
        
def dir_to_strlist(directory):
    l = []
    for obj in directory.GetListOfKeys():
        l.append(obj.GetName())
    return l

class WCSimTest:
    def __init__(self, config_file):
        self.config_file = config_file
        self.testdir = os.path.abspath(os.path.dirname(config_file))
        # Create default name out of bottom level dir name
        self.name = os.path.basename(self.testdir)
        self.description = ''
        
        # Load testcase settings from file and store all attributes in this object
        params = {}
        execfile(self.config_file, {}, params)
        for k,v in params.items():
            setattr(self, k, v)
        
        # Expand full paths
        self.wcsim_macro = os.path.abspath(os.path.join(self.testdir, self.wcsim_macro))
        self.root_macro = os.path.abspath(os.path.join(self.testdir, self.root_macro))
        
        # Find name of file holding events
        self.event_file = os.path.join(self.testdir, find_outfile_name(self.wcsim_macro))
        print 'Event file:', self.event_file
        
        # Generate names of standard and current output files
        self.standard_results = os.path.join(self.testdir, 'standard.root')
        self.current_results = os.path.join(self.testdir, 'current.root')

    def run(self, regen_mc=False, regen_plots=False, html=None):
        print '='*5, 'Run Test:', self.name, '='*5
        self._do_run(regen_mc=regen_mc, regen_plots=regen_plots)
        
        if html: html.header(name=self.name, description=self.description)
        
        return self.compare_hists(self.standard_results, self.current_results, html=html)

    def update(self, regen_mc=False, regen_plots=False):
        print '='*5, 'Update Test:', self.name, '='*5
        self._do_run(regen_mc=regen_mc, regen_plots=regen_plots)
        print 'Copying current results to master file of standard results'
        shutil.copyfile(self.current_results, self.standard_results)
        
    def _do_run(self, regen_mc, regen_plots):
        if regen_mc or target_needs_update(self.event_file, [self.wcsim_macro]):
            self.run_wcsim()
        if regen_plots or target_needs_update(self.current_results, [self.event_file, self.root_macro]):
            self.run_root()
            

    def run_wcsim(self):
        self.run_cmd_in_testdir('WCSim ' + os.path.basename(self.wcsim_macro))
        
    def run_root(self):
        cwd = os.getcwd()
        try:
            os.chdir(self.testdir)
            gSystem.ChangeDirectory(self.testdir)
            gROOT.ProcessLine('.L ' + os.path.basename(self.root_macro))
            event_file = TFile(self.event_file)
            event_tree = event_file.Get('wcsimT')
            outfile = TFile(self.current_results, 'RECREATE')
            outfile.cd()
            ROOT.make_plots(event_file, event_tree, outfile)

            outfile.Close()
            event_file.Close()
        finally:
            os.chdir(cwd)
            
    def run_cmd_in_testdir(self, cmd):
        cwd = os.getcwd()
        try:
            os.chdir(self.testdir)
            print 'Running:', cmd
            os.system(cmd)
        finally:
            os.chdir(cwd)
    
    def compare_hists(self, master_fname, current_fname,html=None):
        master_file = TFile(master_fname)
        current_file = TFile(current_fname)
        
        master_objs = set(dir_to_strlist(master_file))
        current_objs = set(dir_to_strlist(current_file))
        m_only = master_objs.difference(current_objs)
        both = master_objs.intersection(current_objs)
        c_only = current_objs.difference(master_objs)
        
        if len(m_only) != 0:
            print 'WARNING: master contains', ' '.join(m_only), 'and current test does not.'
        if len(c_only) != 0:
            print 'WARNING: current test file contains', ' '.join(list(c_only)), 'and master does not.'
            
        overall_success = True
        for objname in both:
            c_obj = current_file.Get(objname)
            m_obj = master_file.Get(objname)

            prob = m_obj.KolmogorovTest(c_obj)
            
            print "Comparing", objname, ":", c_obj.GetTitle()
            
            if prob > 0.01:
                print "  SUCCESS",
                success = True
            else:
                print "  FAILURE",
                overall_success = False
                success = False
            print ": KS prob =", prob
            
            plotfile = os.path.join(self.testdir, objname+'.png')
            self.draw_hist(plotfile, m_obj, c_obj)
            fit_parameters = self.get_fit(m_obj, c_obj)
            
            if html: html.hist(name=objname, description='', prob=prob,
                               success=success,
                               plotname=os.path.basename(plotfile),
                               parameters=fit_parameters)
        return overall_success
            
    def draw_hist(self, plotfile, master, current):
        c1 = TCanvas('c1', '', 600, 400)
        master.SetLineColor(kBlue)
        current.SetLineColor(kRed)
        current.SetLineStyle(kDashed)
        
        all_min = min(master.GetMinimum(), current.GetMinimum())
        all_max = max(master.GetMaximum(), current.GetMaximum())
        span = all_max - all_min
        master.SetMinimum(all_min - 0.1 * span)
        master.SetMaximum(all_max + 0.1 * span)
            
        master.Draw()
        current.Draw("SAME")
            
        c1.Print(plotfile)

    def get_fit(self, master_hist, current_hist):
        master_funclist = master_hist.GetListOfFunctions()
        current_funclist = current_hist.GetListOfFunctions()

        if master_funclist.GetSize() == 0 or current_funclist.GetSize() == 0:
            return None # Don't plot fit function parameters

        # Assume only 1 fit function
        master_func = master_funclist.At(0)
        current_func = current_funclist.At(0)

        # Make sure these are really functions
        if master_func.Class().GetName() != 'TF1' \
           or current_func.Class().GetName() != 'TF1':
            return None

        npar = master_func.GetNpar()
        parameters = []
        for ipar in xrange(npar):
            parameter = { 'name' : master_func.GetParName(ipar),
                          'm_val': master_func.GetParameter(ipar),
                          'm_err': master_func.GetParError(ipar),
                          'c_val': current_func.GetParameter(ipar),
                          'c_err': current_func.GetParError(ipar) }
            parameter['delta'] = parameter['c_val'] - parameter['m_val'] 
            parameter['sigma'] = abs(parameter['delta']) \
                                 / sqrt(parameter['m_err']**2 +
                                        parameter['c_err']**2)
            parameters.append(parameter)

        return parameters
            
        
class WCSimHtml:
    def __init__(self, htmlname):
        self.htmlname = htmlname
        self.plots = []
        
    def header(self, name, description):
        self.name = name
        self.description = description
    
    def hist(self, name, description, prob, success, plotname, parameters):
        p = {'name':name, 'description':description,
             'prob':prob, 'plotname' : plotname,
             'parameters': parameters}
        if success:
            p['result'] = '<font color="green">Success</font>'
        else:
            p['result'] = '<font color="red">Failure</font>'
        self.plots.append(p)
    
    def write(self):
        self.plots.sort(cmp=lambda x,y: cmp(x['name'], y['name']))
        
        f = file(self.htmlname, 'w')
        f.write(
'''
<html>
  <head>
    <title>WCSim Test: %(name)s</title>
  </head>
  <body>
    <h1>WCSim Test: %(name)s</h1>
    <p>%(description)s</p>
    
''' % { 'name' : self.name, 'description' : self.description})
        
        for p in self.plots:
            f.write(
'''
     <hr>
     <h3>%(name)s: %(result)s</h3>
     <p>%(description)s</p>
     <center>''' % p)

            f.write(
'''     <img src="%(plotname)s"><br>
     <font color="blue">Blue: Standard</font>,  <font color="red">Red: Current Code</font><br>
     <p>KS Probability: %(prob)f</p>''' % p)

            # Optional table showing fit parameters
            if p['parameters']:
                f.write('''
         <table border="1">
         <tr><th>Parameter Name</th><th>Standard</th><th>Current</th><th>Diff</th></tr>
''')
                for par in p['parameters']:
                    f.write('<tr><td>%(name)s</td><td>%(m_val)f (+/- %(m_err)1.3f)</td><td>%(c_val)f (+/- %(c_err)1.3f)</td><td>' % par)
                    if par['sigma'] > 2.0:
                        f.write('<font color="red">')
                    else:
                        f.write('<font color="green">')
                    f.write('%(sigma)1.1f&sigma;</font></td></tr>\n' % par)
                f.write('</table>\n')

            f.write('''
     </center>
''' % p
)

def make_template(testname):

    ## WCSim test config
    f = open('wcsimtest.config', 'w')
    f.write("""# -*- python-*-
description = '''Put your description here.'''
wcsim_macro = '%(testname)s.mac'
root_macro = '%(testname)s.C'
""" % { 'testname' : testname })
    f.close()

    ## WCSim macro
    f = open('%s.mac' % (testname,), 'w')
    f.write('''/run/verbose 0
/tracking/verbose 0
/hits/verbose 0
/WCSim/SavePi0 false
/mygen/generator normal
/gun/particle e-
/gun/energy 1000 MeV
/gun/direction 1 0 0 
/gun/position 1 0 0 

/WCSimIO/RootFile %s.root

/run/beamOn 100
''' % (testname,) )
    f.close()

    ## ROOT macro
    f = open('%s.C' % (testname,), 'w')
    f.write('''void make_plots(TFile *event_file, TTree *T, TFile *out_file)
{
  TH1D *pe = new TH1D("ncher",";hit PMTs per event", 20, 3800, 4150);

  WCSimRootEvent *wcsimrootsuperevent = new WCSimRootEvent();
  wcsimT->SetBranchAddress("wcsimrootevent",&wcsimrootsuperevent);

  // Force deletion to prevent memory leak when issuing multiple
  // calls to GetEvent()
  wcsimT->GetBranch("wcsimrootevent")->SetAutoDelete(kTRUE);
  for (int i=0; i < wcsimT->GetEntries(); i++)
  {
    wcsimT->GetEvent(i);
    WCSimRootTrigger *wcsimrootevent = wcsimrootsuperevent->GetTrigger(0);
    pe->Fill(wcsimrootevent->GetNcherenkovhits());
  }

  out_file->cd();
  pe->Write();
}
''')

#############################################################

#### Parse command line options
from optparse import OptionParser
parser = OptionParser()
parser.add_option('-u', '--update',
                  action='store_true', dest='update', default=False,
                  help='Update "standard" histogram with current results')

parser.add_option('-m', '--regen-mc',
                  action='store_true', dest='regen_mc', default=False,
                  help='Force Monte Carlo to be regenerated')

parser.add_option('-r', '--regen-plots',
                  action='store_true', dest='regen_plots', default=False,
                  help='Force histograms to be regenerated')

parser.add_option('-t', '--text-only',
                  action='store_false', dest='web', default=True,
                  help='Do not open web pages with plots')
                  

parser.add_option('--make-template', action='store', dest='template', default=None,
                  help='''Write a template wcsimtest to current directory for you to edit.
Supplied name is used for .mac and .C files.''')
                  
options, args = parser.parse_args()

if options.template:
    make_template(options.template)
    print 'Writing test template to current directory...'
    sys.exit()

if len(args) == 0: args = ['.']

#### Open runfile
configname = 'wcsimtest.config'
htmlname = 'results.html'
success = True
for arg in args:
    for dirpath, dirnames, filenames in os.walk(arg):
        if configname in filenames:
            testcase = WCSimTest(os.path.join(dirpath, configname))
            if options.update:
                testcase.update(regen_mc=options.regen_mc, regen_plots=options.regen_plots)

            testcase_html = WCSimHtml(os.path.join(dirpath, htmlname))
            result = testcase.run(regen_mc=options.regen_mc, regen_plots=options.regen_plots,
                                  html=testcase_html)
            testcase_html.write()
            if options.web:
                webbrowser.open('file://'+os.path.abspath(testcase_html.htmlname), new=1)
            success = success and result
            
if not success:
    sys.exit(1)

            
