# Sampe setup macro with no visualization

/run/verbose 0
/tracking/verbose 0
/hits/verbose 0

## select the geometry
# Default config if you do nothing is currently SuperK
#
# The tube size is fixed for SK to 20"
# These are fixed geometries for validation
#/WCSim/WCgeom SuperK

#Changes the length of the simulated volume. Is currently only set up for HyperK. 

#/WCSim/WCgeom HyperK #default length is 49500 mm unless changed in /WCSim/HK/PartionLength below.

#/WCSim/HyperK/waterTank_Length 24750. mm # Equivalent length for 10 partitions
#/WCSim/HyperK/waterTank_Length 49500. mm # Equivalent length for 5 partitions
#/WCSim/HyperK/waterTank_Length 61875. mm # Equivalent length for 4 partitions
#/WCSim/HyperK/waterTank_Length 82500. mm # Equivalent length for 3 partitions
#/WCSim/HyperK/waterTank_Length 123750. mm # Equivalent length for 2 partitions
#/WCSim/HyperK/waterTank_Length 247500. mm # Equivalent length for 1 partition

#/WCSim/Construct

#Added for the PMT QE option 08/17/10 (XQ)
# 1. Stacking only mean when the photon is generated
# the QE is applied to reduce the total number of photons
# 2. Stacking and sensitivity detector
# In the stacking part, the maximum QE is applied to reduce
# the total number of photons
# On the detector side, the rest of QE are applied according to QE/QE_max
# distribution. This option is in particular important for the WLS
# 3. The last option means all the QE are applied at the detector
# Good for the low energy running.
/WCSim/PMTQEMethod     Stacking_Only
#/WCSim/PMTQEMethod     Stacking_And_SensitiveDetector
#/WCSim/PMTQEMethod     SensitiveDetector_Only

# command to choose save or not save the pi0 info 07/03/10 (XQ)
/WCSim/SavePi0 false

## select the input nuance-formatted vector file
## you can of course use your own
#/mygen/vecfile inputvectorfile
#/mygen/vecfile h2o.2km.001-009x3_G4.kin
#/mygen/vecfile mu+.out

## Dark Noise: default are nominal values from PMT and is ON
## Switch OFF by setting rate and/or conversion factor to 0 below:
#/DarkRate/SetDarkRate 0.01 Hz 
#/DarkRate/SetConvert 0                  # command to multiply the dark rate.


# Or you can use the G4 Particle Gun
/mygen/generator normal
/gun/particle e-
#/gun/particle pi0
/gun/energy 500 MeV
/gun/direction 1 0 0 
/gun/position 0 0 0  

## change the name of the output root file, default = wcsim.root

/WCSimIO/RootFile wcsimtest.root

/run/beamOn 1000
#exit
