# Set tuning parameters
# Set rayff>0 to scale the Rayleigh mean free path in water hard-coded in WCSimContructMaterials.cc, based on SK data
# Set rayff<=0 to use the Rayleigh mean free path in water calculated by Geant4
# If activating Raman scattering, using the Geant4 value is the current recommendation (the SK measurement of Rayleigh scattering may have a Raman effect)
/WCSim/tuning/abwff 1.30
/WCSim/tuning/rgcff 0.32
/WCSim/tuning/rayff 0.75
/WCSim/tuning/bsrff 2.50
/WCSim/tuning/mieff 0.0

# Parameters to set up Top Veto - jl145
# Set to "1" to turn on top veto.
/WCSim/tuning/topveto 0
# Set top veto PMT spacing in cm.
/WCSim/tuning/tvspacing 100

# Input file to set photocathode parameters
/WCSim/tuning/PMTCathodePara data/CathodeParameters.txt

/WCSim/tuning/WCODWLSCladdingReflectivity 0.99
/WCSim/tuning/WCODTyvekReflectivity 0.95
/WCSim/tuning/WCODTyvekOutwallReflectivity 0.87

