## Stolen from T.Feusseul nuPRISM visu of mPMTs

## Construct the Outer Detector
/WCSim/WCgeom HyperKWithOD
/WCSim/HyperKOD/PMTODRadius 3inch
/WCSim/HyperKOD/ODLateralWaterDepth 1 m
/WCSim/HyperKOD/ODHeightWaterDepth 2 m
/WCSim/HyperKOD/ODDeadSpace 600 mm
/WCSim/HyperKOD/ODTyvekSheetThickness 2 mm
/WCSim/HyperKOD/ODWLSPlatesThickness 1 cm
/WCSim/HyperKOD/ODWLSPlatesLength 60 cm
/WCSim/HyperKOD/PMTODperCellHorizontal 1
/WCSim/HyperKOD/PMTODperCellVertical 1
/WCSim/HyperKOD/PMTODPercentCoverage 1
/WCSim/HyperKOD/ODPMTShift 0 m
/WCSim/Construct

# Use this open statement to create an OpenGL view:
/vis/open OGLSQt

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90. 180.
#
# Specify zoom value:
#/vis/viewer/zoom 1.4
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
