# nuPRISMBeamTest WCTE macro with no visualization

/run/verbose 1
/tracking/verbose 0
/hits/verbose 0
#/control/execute vis.mac
#/vis/open OGLSQt

## select the geometry
# Default config if you do nothing is currently SuperK
# Nominal geometry for WCTE is nuPRISMBeamTest_16cShort_mPMT which is uncommented


#Use mPMTs settings and beam test geometry 
#/WCSim/WCgeom nuPRISMBeamTest_mPMT ## this is 18c5r from the original design
/WCSim/WCgeom nuPRISMBeamTest_16cShort_mPMT ## this is 16c4r from CAD
# Rotate barrel by half a tower (needed for correct WCTE geometry)
/WCSim/Geometry/RotateBarrelHalfTower true

# True --> default replica method to place PMTs. False --> new placement method 
/WCSim/PMT/ReplicaPlacement false

##################
# AmBe CALIBRATION SOURCE
##################
# - BGO Placement: Default in source code is false. If set to true, you'll place the BGO inside
# the detector geometry at (0,0,0) position. This is only supported if you use ambeevt generator
# so you can see the tag scintillation light for the AmBe source.
#/WCSim/BGOPlacement true
# Note that /WCSim/BGOPlacement *must* be set before /WCSim/Construct

# - /WCSim/SaveCapture & /process/inactivate nKiller: Default not set.
# Also specially needed for AmBe calibration. The first command makes sure the Capture processes
# are being saved. The second one ensures Geant4 is not killing neutrons too early in the run,
# so we can have neutronCapture at any time in the run.
#/WCSim/SaveCapture true
#/process/inactivate nKiller

############################################################################################
##These comments are only useful when using /WCSim/PMT/ReplicaPlacement false
# Apply random fluctuation to PMT placement. Argument specifies the Gaussian 1 sigma value
/WCSim/PMT/PositionVariation 0 mm
# Change the ID radius at top, middle and bottom for PMT placement
/WCSim/PMT/TankRadiusChange 0 0 0 mm
# Read PMT positions, ID, orientation from input file. This overrides the auto positioning
/WCSim/PMT/PositionFile data/mPMT_Position_WCTE.txt
# To import CDS into simulation
# 1. Downland the CDS CAD model from WCTE webpage (https://wcte.hyperk.ca/wg/calibration/cds-system/cds-arm-cad-for-physics-simulation/arm-for-simulation-ascii-v2.zip/view), unzip it and set the path
# 2. Use the following PMT position file where mPMT id 90 and 96 are disabled 
#/WCSim/Geometry/SetCDSFile path_to_CDS_file
#/WCSim/PMT/PositionFile data/mPMT_Position_WCTE_CDS.txt
############################################################################################

# Set Gadolinium doping (concentration is in percent)
#/WCSim/DopingConcentration 0.1
#/WCSim/DopedWater false
/WCSim/Construct
## OR for single mPMT mode or updating mPMT parameters:
#/control/execute macros/mPMT_nuPrism1.mac         ## mPMT options: mPMT_nuPrism1.mac and 2.mac

#Added for the PMT QE option 08/17/10 (XQ)
# 1. Stacking only mean when the photon is generated
# the QE is applied to reduce the total number of photons
# 2. Stacking and sensitivity detector
# In the stacking part, the maximum QE is applied to reduce
# the total number of photons
# On the detector side, the rest of QE are applied according to QE/QE_max
# distribution. This option is in particular important for the WLS
# 3. The third option means all the QE are applied at the detector
# Good for the low energy running.
# 4. Switch off the QE, ie. set it at 100%

/WCSim/PMTQEMethod     Stacking_Only
#/WCSim/PMTQEMethod     Stacking_And_SensitiveDetector
#/WCSim/PMTQEMethod     SensitiveDetector_Only
#/WCSim/PMTQEMethod     DoNotApplyQE

#turn on or off the collection efficiency
/WCSim/PMTCollEff on

# command to choose save or not save the pi0 info 07/03/10 (XQ)
/WCSim/SavePi0 false

#choose the Trigger & Digitizer type (and options)
/DAQ/Digitizer SKI
/DAQ/Trigger NDigits

#grab the other DAQ options (thresholds, timing windows, etc.)
/control/execute macros/daq.mac

# setseed - option to change seeds
#/random/setSeeds 2 1
#/WCSim/random/seed 4


# default dark noise frequency (and conversion factor) is PMT property (NEW), set in the code.
# Below gives possibility to overwrite nominal values, eg. to switch OFF the Dark Noise.
#/DarkRate/SetDarkRate 0 kHz   #Turn dark noise off
#/DarkRate/SetDarkRate 4.2 kHz #This is the value for SKI set in SKDETSIM.


# Select which time window(s) to add dark noise to
#/DarkRate/SetDarkMode 0 to add dark noise to a time window starting at
#/DarkRate/SetDarkLow to /DarkRate/SetDarkHigh [time in ns]
#/DarkRate/SetDarkMode 1 adds dark noise hits to a window of
#width /DarkRate/SetDarkWindow [time in ns] around each hit
#i.e. hit time ± (/DarkRate/SetDarkWindow) / 2
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkHigh 100000
/DarkRate/SetDarkLow 0
/DarkRate/SetDarkWindow 4000

#Uncomment one of the lines below if you want to use the OGLSX or RayTracer visualizer
#/control/execute macros/visOGLSX.mac
#/control/execute macros/visRayTracer.mac
#/control/execute macros/visOGLQT.mac             ## NEW

## select the input nuance-formatted vector file
## you can of course use your own
#/mygen/generator muline
#/mygen/vecfile inputvectorfile
#/mygen/vecfile h2o.2km.001-009x3_G4.kin
#/mygen/vecfile mu+.out

# Or you can use the G4 Particle Gun
# for a full list of /gun/ commands see:
# http://geant4.web.cern.ch/geant4/G4UsersDocuments/UsersGuides/ForApplicationDeveloper/html/Control/UIcommands/_gun_.html
#/mygen/generator gun
#/gun/particle e-
#/gun/particle pi0
#/gun/energy 500 MeV
#/gun/direction 0 1 0
#/gun/position 0 0 0  

# Or you can use the G4 General Particle Source
# you can do a lot more with this than a monoenergetic, monodirectional, single-particle gun
# for a full list of /gps/ commands see:
# https://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/ForApplicationDeveloper/html/ch02s07.html
/mygen/generator gps
/gps/particle e-
/gps/energy 500 MeV
/gps/direction -1 0 0
/gps/position 165 0 0

# Or you can use the laser option
# This is equivalent to the gps command, except that the gps particle energies are saved ignoring their mass
# for a full list of /gps/ commands see:
# https://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/ForApplicationDeveloper/html/ch02s07.html
# It is used for laser calibration simulation
#/mygen/generator laser
#/gps/particle opticalphoton
#/gps/energy 3.505 eV
#/gps/direction 0 0 1
#/gps/position 0 0 0
#/gps/number 10000
#/gps/ang/type iso
#/gps/ang/mintheta 0 deg
#/gps/ang/maxtheta 10 deg
#/gps/ang/minphi 0 deg
#/gps/ang/maxphi 360 deg

# Or you can use the AmBe Calibration Source Generator.
# This launches two primary particles in a random direction from the (0,0,0): one neutron and one gamma.
# The energy of the gamma can be:
# - 4.4 MeV 65% of the time.
# - 7.7 MeV 8%  of the time.
# - 0.0 MeV 26% of the time.
# Neutron Energy is taken from a simulated realistic AmBe Spectrum depending on the Gamma Energy.
# In order to run this correctly, the AmBe source must be in the geometry & neutron capture must be activated - for details see the "AmBe CALIBRATION SOURCE" section above
#/mygen/generator ambeevt

##################
# TRACKING
##################
## Commands to control which true particle tracks are tracked and saved to the output file:
## By default, save all tracks in the chain from primaries to those that produce Cherenkov photons that produce hits
## To disable this behaviour and only save tracks of particular creation processes and particle types, set to false
/Tracking/saveHitProducingTracks true
## By default, all electrons, muons, pions, kaons, protons and neutrons are saved, and particles created by Decay, conv,
## nCapture or OpWLS processes
## Add additional PDG codes of particle types or additional Geant4 process names of creation processes of tracks to save
## Note that optical photons have PDG code 0 in Geant4
#/Tracking/trackParticle 0
#/Tracking/trackProcess Cerenkov
## Due to the typically very large number of optical photons, a fraction can be tracked by setting the percentage to randomly draw
## Note that the value is a percentage from 0.0 to 100.0, not fraction 0.0 to 1.0
/Tracking/fractionOpticalPhotonsToDraw 0.0

## change the name of the output root file, default = wcsim.root
/WCSimIO/RootFile wcsim.root

## Boolean to select whether to save the NEUT RooTracker vertices in the output file, provided you used
## a NEUT vector file as input
/WCSimIO/SaveRooTracker 0

## set a timer running on WCSimRunAction
#/WCSimIO/Timer false

/run/beamOn 1
#exit

