/********************************************************************
* WCMapDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error WCMapDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableWCMapDict();
extern void G__cpp_setup_inheritanceWCMapDict();
extern void G__cpp_setup_typetableWCMapDict();
extern void G__cpp_setup_memvarWCMapDict();
extern void G__cpp_setup_globalWCMapDict();
extern void G__cpp_setup_memfuncWCMapDict();
extern void G__cpp_setup_funcWCMapDict();
extern void G__set_cpp_environmentWCMapDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCEvent.h"
#include "Xin_Draw.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WCMapDictLN_TClass;
extern G__linked_taginfo G__WCMapDictLN_TBuffer;
extern G__linked_taginfo G__WCMapDictLN_TMemberInspector;
extern G__linked_taginfo G__WCMapDictLN_TObject;
extern G__linked_taginfo G__WCMapDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__WCMapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WCMapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCMapDictLN_TList;
extern G__linked_taginfo G__WCMapDictLN_TString;
extern G__linked_taginfo G__WCMapDictLN_TClonesArray;
extern G__linked_taginfo G__WCMapDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WCMapDictLN_WCSimRootCherenkovHit;
extern G__linked_taginfo G__WCMapDictLN_WCSimRootCherenkovDigiHit;
extern G__linked_taginfo G__WCMapDictLN_WCSimRootTrigger;
extern G__linked_taginfo G__WCMapDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__WCMapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCMapDictLN_WCSimRootEvent;
extern G__linked_taginfo G__WCMapDictLN_WCSimRootPMT;
extern G__linked_taginfo G__WCMapDictLN_WCSimRootGeom;
extern G__linked_taginfo G__WCMapDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__WCMapDictLN_MCEvent;
extern G__linked_taginfo G__WCMapDictLN_TQObject;
extern G__linked_taginfo G__WCMapDictLN_TGWindow;
extern G__linked_taginfo G__WCMapDictLN_TGObject;
extern G__linked_taginfo G__WCMapDictLN_TGFrame;
extern G__linked_taginfo G__WCMapDictLN_TGCompositeFrame;
extern G__linked_taginfo G__WCMapDictLN_TGMainFrame;
extern G__linked_taginfo G__WCMapDictLN_TGCheckButton;
extern G__linked_taginfo G__WCMapDictLN_TGListBox;
extern G__linked_taginfo G__WCMapDictLN_TBox;
extern G__linked_taginfo G__WCMapDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__WCMapDictLN_TGStatusBar;
extern G__linked_taginfo G__WCMapDictLN_TGTextBuffer;
extern G__linked_taginfo G__WCMapDictLN_TGTextEntry;
extern G__linked_taginfo G__WCMapDictLN_TPad;
extern G__linked_taginfo G__WCMapDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__WCMapDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__WCMapDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__WCMapDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__WCMapDictLN_TH2F;
extern G__linked_taginfo G__WCMapDictLN_TFile;
extern G__linked_taginfo G__WCMapDictLN_TTree;
extern G__linked_taginfo G__WCMapDictLN_TBranch;
extern G__linked_taginfo G__WCMapDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__WCMapDictLN_TEllipse;
extern G__linked_taginfo G__WCMapDictLN_Xin_Draw;
extern G__linked_taginfo G__WCMapDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__WCMapDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
